<!-- Title subtitle centered mini template  -->
<section class="breadcrumb_area" style="z-index: unset !important;">
    <div class="container">
        <?=
            $this->MelisTag(
                $this->idPage,
                'contact-html-1',
                'html',
                '<div class="breadcrumb_content text-center">
                    <h1 class="f_p f_700 f_size_50 w_color l_height50 mb_20">Contact Us</h1>
                    <p class="f_400 w_color f_size_16 l_height26">Why I say old chap that is spiffing off his nut arse pear shaped plastered<br> Jeffrey bodge barney some dodgy.!!</p>
                </div>'
            )
        ?>
    </div>
</section>

<section class="contact_info_area sec_pad bg_color">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 pr-0">
                <?=
                    $this->MelisTag(
                        $this->idPage,
                        'contact-html-2',
                        'html',
                        '<div class="info_item">
                            <h3>Office Address</h3>
                            <p>4, rue du Dahomey 75011 Paris, France</p>
                        </div>
                        <div class="info_item">
                            <h3>Contact Info</h3>
                            <p>Phone: (+33) 972 386 280<br>Email: contact@melistechnology.com </p>
                        </div>'
                    )
                ?>
            </div>
            <div class="col-lg-8">
                <div class="mapbox">
                    <div id="mapBox" class="row m0" data-lat="48.850973" data-lon="2.382171" data-zoom="16" data-info="4, rue du Dahomey 75011 Paris, France" data-mlat="48.850973" data-mlon="2.382171">
                    </div>
                </div>
                <div style="<?= ($this->renderMode == 'melis') ? : 'display: none;' ?>">
                    <div class="col-xs-6" id="map-lat">
                        <?= $this->MelisTag($this->idPage, 'contact_gmap_lat', 'textarea', '48.850973') ?>
                    </div>
                    <div class="col-xs-6" id="map-long">
                        <?= $this->MelisTag($this->idPage, 'contact_gmap_long', 'textarea', '2.382171'); ?>
                    </div>
                </div>
            </div>
        </div>
        <?= $this->prospectForm ?>
    </div>
</section>
