<!-- Title subtitle centered mini template  -->
<section class="breadcrumb_area" style="z-index: unset !important;">
    <div class="container">
        <?=
            $this->MelisTag(
                $this->idPage,
                'contact-html-1',
                'html',
                '<div class="breadcrumb_content text-center">
                    <h1 class="f_p f_700 f_size_50 w_color l_height50 mb_20">Contact Us</h1>
                    <p class="f_400 w_color f_size_16 l_height26">Why I say old chap that is spiffing off his nut arse pear shaped plastered<br> Jeffrey bodge barney some dodgy.!!</p>
                </div>'
            )
        ?>
    </div>
</section>

<section class="contact_info_area sec_pad bg_color">
    <div class="container">
        <?= $this->prospectForm ?>
    </div>
</section>
