<?= $this->MelisDragDropZone($this->idPage, "dragdropzone_faq_1") ?>
    <div class="clear"></div>
<section class="faq_area bg_color sec_pad">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 pr_50">
                <!-- Faq List -->
                <?= $this->faqList ?>
            </div>
            <div class="col-lg-8">
                <div class="tab-content faq_content" id="myTabContent">
                    <div class="tab-pane fade show active" id="page_tab_<?= $this->faqValues1PageId ?>" role="tabpanel" aria-labelledby="page_tab_<?= $this->faqValues1PageId ?>-tab">
                        <h3 class="f_p f_size_22 f_500 t_color3 mb_20">
                            <?=
                                $this->MelisTag(
                                    $this->idPage,
                                    'faq-values-title-1',
                                    'textarea',
                                    'Questions about delivery'
                                )
                            ?>
                        </h3>
                        <div id="accordion">
                            <!-- Faq values -->
                            <?= $this->faqValues1 ?>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="page_tab_<?= $this->faqValues2PageId ?>" role="tabpanel" aria-labelledby="page_tab_<?= $this->faqValues2PageId ?>-tab">
                        <h3 class="f_p f_size_22 f_500 t_color3 mb_20">
                            <?=
                                $this->MelisTag(
                                    $this->idPage,
                                    'faq-values-title-2',
                                    'textarea',
                                    'Question about the product'
                                )
                            ?>
                        </h3>
                        <div id="accordion">
                            <!-- Faq values -->
                            <?= $this->faqValues2 ?>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="page_tab_<?= $this->faqValues3PageId ?>" role="tabpanel" aria-labelledby="page_tab_<?= $this->faqValues2PageId ?>-tab">
                        <h3 class="f_p f_size_22 f_500 t_color3 mb_20">
                            <?=
                                $this->MelisTag(
                                    $this->idPage,
                                    'faq-values-title-3',
                                    'textarea',
                                    'Questions about payment'
                                )
                            ?>
                        </h3>
                        <div id="accordion">
                            <!-- Faq values -->
                            <?= $this->faqValues3 ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?= $this->MelisDragDropZone($this->idPage, "dragdropzone_faq_2") ?>
<div class="clear"></div>
