<!-- Title subtitle centered mini template  -->
<section class="breadcrumb_area" style="z-index: unset !important;">
    <div class="container">
        <?=
            $this->MelisTag(
                $this->idPage,
                'faq-html-1',
                'html',
                '<div class="breadcrumb_content text-center">
                    <h1 class="f_p f_700 f_size_50 w_color l_height50 mb_20">FAQ</h1>
                    <p class="f_400 w_color f_size_16 l_height26">Why I say old chap that is spiffing off his nut arse pear shaped plastered<br> Jeffrey bodge barney some dodgy.!!</p>
                </div>'
            )
        ?>
    </div>
</section>

<section class="faq_area bg_color sec_pad">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 pr_50">
                <!-- Faq List -->
                <?= $this->faqList ?>
            </div>
            <div class="col-lg-8">
                <div class="tab-content faq_content" id="myTabContent">
                    <div class="tab-pane fade show active" id="page_tab_<?= $this->faqValues1PageId ?>" role="tabpanel" aria-labelledby="page_tab_<?= $this->faqValues1PageId ?>-tab">
                        <h3 class="f_p f_size_22 f_500 t_color3 mb_20">
                            <?=
                                $this->MelisTag(
                                    $this->idPage,
                                    'faq-values-title-1',
                                    'textarea',
                                    'Questions about delivery'
                                )
                            ?>
                        </h3>
                        <div id="accordion">
                            <!-- Faq values -->
                            <?= $this->faqValues1 ?>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="page_tab_<?= $this->faqValues2PageId ?>" role="tabpanel" aria-labelledby="page_tab_<?= $this->faqValues2PageId ?>-tab">
                        <h3 class="f_p f_size_22 f_500 t_color3 mb_20">
                            <?=
                                $this->MelisTag(
                                    $this->idPage,
                                    'faq-values-title-2',
                                    'textarea',
                                    'Question about the product'
                                )
                            ?>
                        </h3>
                        <div id="accordion">
                            <!-- Faq values -->
                            <?= $this->faqValues2 ?>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="page_tab_<?= $this->faqValues3PageId ?>" role="tabpanel" aria-labelledby="page_tab_<?= $this->faqValues2PageId ?>-tab">
                        <h3 class="f_p f_size_22 f_500 t_color3 mb_20">
                            <?=
                                $this->MelisTag(
                                    $this->idPage,
                                    'faq-values-title-3',
                                    'textarea',
                                    'Questions about payment'
                                )
                            ?>
                        </h3>
                        <div id="accordion">
                            <!-- Faq values -->
                            <?= $this->faqValues3 ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>