<?= $this->MelisDragDropZone($this->idPage, "dragdropzone_faq_1") ?>
    <div class="clear"></div>
<section class="faq_area bg_color sec_pad">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 pr_50">
                <!-- Faq List -->
                <?= $this->faqList ?>
            </div>
            <div class="col-lg-8">
                <div class="tab-content faq_content" id="myTabContent">
                    <?php
                        $first = false;
                    ?>
                    <?php foreach ($this->pages as $page) : ?>
                        <div class="tab-pane fade show <?= (!$first) ? 'active' : '' ?>" id="page_tab_<?= $page->page_id ?>" role="tabpanel" aria-labelledby="page_tab_<?= $page->page_id ?>-tab">
                            <h3 class="f_p f_size_22 f_500 t_color3 mb_20">
                                <?=
                                    $this->MelisTag(
                                        $this->idPage,
                                        'faq-values-title-1',
                                        'textarea',
                                        'Questions about delivery'
                                    )
                                ?>
                            </h3>
                            <div id="accordion<?= $page->page_id ?>">
                                <!-- Faq values -->
                                <?= $this->{'faqValues' . $page->page_id} ?>
                            </div>
                        </div>

                        <?php
                            if (! $first)
                                $first = true;
                        ?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</section>
<?= $this->MelisDragDropZone($this->idPage, "dragdropzone_faq_2") ?>
<div class="clear"></div>
