<?=
    $this->MelisTag(
        $this->idPage,
        'static-html-1',
        'html',
        '<section class="breadcrumb_area" style="z-index: unset !important;">
            <div class="container">
                <div class="breadcrumb_content text-center">
                    <h1 class="f_p f_700 f_size_50 w_color l_height50 mb_20">Accessible, Convenient & Manageable</h1>
                    <p class="f_400 w_color f_size_16 l_height26">The full monty burke posh excuse my French Richard cheeky bobby spiffing crikey<br> Why gormless, pear shaped.!</p>
                </div>
            </div>
        </section>'
    )
?>
<br>
<?=
$this->MelisTag(
    $this->idPage,
    'mixed-html-1',
    'html',
    '<div>
            <h5><strong>Lorem ipsum dolor</strong></h5>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            <br><br>
            <h5><strong>Lorem ipsum dolor</strong></h5>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            <br><br>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </div>'
)
?>
<br>
<?=
$this->MelisTag(
    $this->idPage,
    'mixed-textarea-1',
    'textarea',
    '<span style="color: #2880b9;">Lorem ipsum dolor</span><br>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
)
?>
<br>
<?=
$this->MelisTag(
    $this->idPage,
    'mixed-media-1',
    'media',
    '<center>
        <img src="/MelisDemoCms/img/erp-home/erp_dashboard.jpg" alt="">
    </center>'
)
?>
<?= $this->staticSlider ?>
