<section class="erp_testimonial_area sec_pad">
    <div class="container">
        <?php if (! empty($this->listofpages)) : ?>
        <div class="row">
            <div class="erp_testimonial_info owl-carousel">
                <?php foreach ($this->listofpages as $key => $page) : ?>
                    <div class="erp_testimonial_item">
                        <div class="content">
                            <p><?= $page->page_tags['testi-html-1'] ?></p>
                        </div>
                        <div class="media">
                            <div class="media-body">
                                <h5><?= $page->page_tags['testi-textarea-1'] ?></h5>
                                <p><?= $page->page_tags['testi-textarea-2'] ?></p>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <?php else : ?>
            <div class="alert warning">
                <div class="alert_body">
                    <i class="icon-close"></i>
                    <?=
                        $this->siteTranslate(
                            'tr_demo_meliscms_no_result',
                            $this->SiteConfig('default_lang_id'),
                            $this->SiteConfig('site_id')
                        )
                    ?>
                </div>
            </div>
        <?php endif ?>
    </div>
</section>