<?php
    $urlQryStr = [];

    // Site Search
    if ($this->siteSearchKey)
    {
        $urlQryStr['keyword'] = $this->siteSearchKey;
    }

    // News Search
    if ($this->searchKey) {
        $urlQryStr['search'] = $this->searchKey;
    }
?>
<?php if ($this->pageCount) : ?>
    <ul class="col-lg-12 list-unstyled page-numbers shop_page_number text-left mt_30">
        <!-- Previous button -->
        <?php if (isset($this->previous)) : ?>
            <li>
                <a class="previous page-numbers" href="<?= $this->MelisLink($this->idPage, true) . '?' . http_build_query(array_merge($urlQryStr, ['current' => $this->previous])) ?>">
                    <i class="ti-arrow-left"></i>
                </a>
            </li>
        <?php else : ?>
            <li><a class="previous page-numbers disabled" href="#"><i class="ti-arrow-left"></i></a></li>
        <?php endif; ?>

        <!-- Pages -->
        <?php foreach ($this->pagesInRange as $page) : ?>
            <?php if ($page >= ($this->current - $this->nbPageBeforeAfter) && $page <= ($this->current + $this->nbPageBeforeAfter)) : ?>
                <?php if ($page != $this->current) : ?>
                    <li>
                        <a class="page-numbers" href="<?= $this->MelisLink($this->idPage, true) . '?' . http_build_query(array_merge($urlQryStr, ['current' => $page])) ?>"><?= $page ?>
                        </a>
                    </li>
                <?php else : ?>
                    <li><span aria-current="page" class="page-numbers current"><?= $page ?></span></li>
                <?php endif; ?>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next button -->
        <?php if (isset($this->next)) : ?>
            <li>
                <a class="next page-numbers" href="<?= $this->MelisLink($this->idPage, true) . '?' . http_build_query(array_merge($urlQryStr, ['current' => $this->next])) ?>">
                    <i class="ti-arrow-right"></i>
                </a>
            </li>
        <?php else : ?>
            <li><a class="next page-numbers disabled" href="#"><i class="ti-arrow-right"></i></a></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>
