<section class="blog_area sec_pad">
    <div class="container">
        <div id="<?php echo $this->pluginId?>">
            <div class="row">
                <div class="col-lg-12">
                    <div class="filter-top" id="news-list-plugin">
                            <form
                                action=""
                                class="contact_form_box apply_form"
                                method="get"
                                novalidate="novalidate"
                                style="width: 100%;"
                            >
                                <div class="row">
                                    <div class="col-lg-3">
                                        <div class="single-aside search-aside search-box">
                                            <div class="form-group text_box">
                                                <input
                                                    type="text"
                                                    id="date-min"
                                                    name="date_min"
                                                    placeholder="Date from"
                                                    value="<?php echo $this->dateMin?>"
                                                    readonly
                                                >
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-3">
                                        <div class="single-aside search-aside search-box">
                                            <div class="form-group text_box">
                                                <input
                                                    type="text"
                                                    id="date-max"
                                                    name="date_max"
                                                    placeholder="Date to"
                                                    value="<?php echo $this->dateMax?>"
                                                    readonly
                                                >
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-3">
                                        <button type="submit" class="btn_three mt_c20" style="height: 60px;">Filter</button>
                                    </div>
                                    <div class="col-lg-3">
                                        <div class="blog-sidebar float-right">
                                            <div class="widget sidebar_widget widget_search">
                                                <div class="search-form input-group">
                                                    <input
                                                        type="text"
                                                        class="form-control widget_input"
                                                        placeholder="Search news"
                                                        name="search"
                                                        value="<?php echo $this->searchKey?>"
                                                        required=""
                                                        style="height: 60px;"
                                                    >
                                                    <button type="submit"><i class="ti-search"></i></button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                    </div>
                    <div class="row">
                        <?php if ($this->listNews->count()) : ?>
                            <?php foreach ($this->listNews as $key => $news) : ?>
                                <div class="col-lg-4 col-sm-4">
                                    <div class="blog_grid_item mb-30">
                                        <div class="blog_img">
                                            <img src="<?= $this->basePath($news['cnews_image1']) ?? '' ?>" alt="">
                                        </div>
                                        <div class="blog_content">
                                            <div class="entry_post_info">
                                                <a href="#"><?= $news['newsDateFormated'] ?></a>
                                            </div>
                                            <a href="#">
                                                <h5 class="f_p f_size_20 f_500 t_color mb_20"><a href="<?= $news['newsLink'] ?>"><?= $news['cnews_title'] ?></a></h5>
                                            </a>
                                            <p class="f_400 mb-0"><?= $news['cnews_subtitle'] ?></p>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                            <!-- Pagination Plugin -->
                            <?=
                                $this->paginationControl(
                                    $this->listNews,
                                    'Sliding',
                                    'MelisDemoCms/plugins/list-paginator',
                                    [
                                        'searchKey' => $this->searchKey,
                                        'nbPageBeforeAfter' => $this->nbPageBeforeAfter
                                    ]
                                )
                            ?>
                        <?php else : ?>
                            <div class="alert warning" style="width: 100%;">
                                <div class="alert_body">
                                    <i class="icon-close"></i>
                                    <?=
                                        $this->siteTranslate(
                                            'tr_demo_meliscms_no_result',
                                            $this->SiteConfig('default_lang_id'),
                                            $this->SiteConfig('site_id')
                                        )
                                    ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
