<?php
$widths = null;

if ($this->fromDragDropZone) {
    $widths = "$this->widthDesktop $this->widthTablet $this->widthMobile";
}
?>
<?php if (! empty($this->news)) : ?>
    <div id="<?= $this->pluginId ?>" class="<?= $widths ?> blog_single mb_50">
        <?php if (! empty($this->news['cnews_image1'])) : ?>
            <img class="img-fluid" src="<?= $this->news['cnews_image1']; ?>" alt="" style="height: auto; width: 100%; object-fit: cover;">
        <?php else : ?>
            <img class="img-fluid" src="<?= $this->basePath('MelisDemoCms/img/blog-grid/blog_single.png') ?>" alt="">
        <?php endif; ?>
        <div class="blog_content">
            <div class="post_date">
                <h2><?= date('d', strtotime($this->news['cnews_publish_date'])) ?> <span><?= date('M Y', strtotime($this->news['cnews_publish_date'])) ?></span></h2>
            </div>
            <div class="entry_post_info">
            </div>
            <a href="#">
                <h5 class="f_p f_size_20 f_500 t_color mb-30"><?= $this->news['cnews_title'] ?></h5>
            </a>

            <?php 
                for ($i = 1; $i <= 10; $i++) { ?>
                    <p class="f_400 mb-30"><?= $this->news['cnews_paragraph'.$i] ?></p>
            <?php    }
            ?>
        </div>
    </div>
<?php else : ?>
    <div class="alert warning">
        <div class="alert_body">
            <i class="icon-close"></i>
            <?=
                $this->siteTranslate(
                    'tr_demo_meliscms_no_result',
                    $this->SiteConfig('default_lang_id'),
                    $this->SiteConfig('site_id')
                )
            ?>
        </div>
    </div>
<?php endif; ?>