<div class="pr_70">
    <div class="job_info">
        <div class="info_head">
            <i class="ti-receipt"></i>
            <h6 class="f_p f_600 f_size_18 t_color3">
                Unique Elements
            </h6>
        </div>
        <div class="info_item">
            <h6>Owner:</h6>
            <p>Droit Theme</p>
        </div>
        <div class="info_item">
            <h6>Live Time:</h6>
            <p>2 Working Days</p>
        </div>
        <div class="info_item">
            <h6>Service Cost:</h6>
            <p>$250.00</p>
        </div>
        <div class="info_item">
            <h6>Quality:</h6>
            <p>High</p>
        </div>
        <div class="info_item">
            <h6>Experience</h6>
            <p>3 Years</p>
        </div>
    </div>
</div>