<div class="row mt_70">
    <div class="col-lg-6 pr_70">
        <h4 class="h_title">Big Text Dropcap</h4>
        <p class="drop_text"><span>K</span>aking cakes buggered my lady up the duffummm I'm telling skive off Richard Oxford it's all gone to pot lavatory codswallop I don't get shirty with me, lost the plot up the kyver plastered mufty the full monty bleeding tosser cheeky what a load of rubbish excuse my French. A cheeky fanny around.!</p>
    </div>
    <div class="col-lg-6 pr_70">
        <h4 class="h_title">Rectangle Dropcap</h4>
        <p class="drop_text"><span><img src="/MelisDemoCms/img/b.png" alt=""></span>aking cakes buggered my lady up the duffummm I'm telling skive off Richard Oxford it's all gone to pot lavatory codswallop I don't get shirty with me, lost the plot up the kyver plastered mufty the full monty bleeding tosser cheeky what a load of rubbish excuse my French. A cheeky fanny around.!</p>
    </div>
</div>