<section class="erp_features_area_two sec_pad">
    <div class="container">
        <div class="row erp_item_features align-items-center flex-row-reverse">
            <div class="col-lg-6">
                <div class="erp_features_img_two">
                    <div class="img_icon"><span class="pluse_1"></span><span class="pluse_2"></span><i class="icon_lightbulb_alt"></i></div>
                    <img src="/MelisDemoCms/img/erp-home/crm_img1.jpg" alt="">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="erp_content_two">
                    <div class="hosting_title erp_title">
                        <h2>Nurture Your Customers Using Advanced CRM</h2>
                        <p>Cack brolly butty grub chancer smashing brilliant vagabond, chimney pot blower such a fibber ummm I'm telling chinwag he lost his bottle.!</p>
                    </div>
                    <div class="media erp_item">
                        <div class="icon">
                            <i class="icon_menu-square_alt2"></i>
                        </div>
                        <div class="media-body">
                            <h5>Everybody Gets a Dashboard</h5>
                        </div>
                    </div>
                    <div class="media erp_item">
                        <div class="icon green">
                            <i class="icon_ribbon_alt"></i>
                        </div>
                        <div class="media-body">
                            <h5>Complete Leave Management</h5>
                        </div>
                    </div>
                    <a href="#" class="erp_btn_learn">Learn More<i class="arrow_right"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>