<section class="erp_service_area sec_pad" style="padding-top: 0px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-sm-6">
                <div class="erp_service_item pr_70">
                    <img src="/MelisDemoCms/img/erp-home/erp_icon1.png" alt="">
                    <a href="#"><h3 class="h_head">Secured Cloud</h3></a>
                    <p>Bloke fantastic bubble and squeak do one what a plonker nancy boy burke fanny around.</p>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="erp_service_item pr_70 pl_10">
                    <img src="/MelisDemoCms/img/erp-home/erp_icon2.png" alt="">
                    <a href="#"><h3 class="h_head">Single Platform</h3></a>
                    <p>Bloke fantastic bubble and squeak do one what a plonker nancy boy burke fanny around.</p>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="erp_service_item pl_70">
                    <img src="/MelisDemoCms/img/erp-home/erp_icon3.png" alt="">
                    <a href="#"><h3 class="h_head">Implement Yourself</h3></a>
                    <p>Bloke fantastic bubble and squeak do one what a plonker nancy boy burke fanny around.</p>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="erp_service_item pr_70">
                    <img src="/MelisDemoCms/img/erp-home/erp_icon4.png" alt="">
                    <a href="#"><h3 class="h_head">Multi Regional</h3></a>
                    <p>Bloke fantastic bubble and squeak do one what a plonker nancy boy burke fanny around.</p>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="erp_service_item pl_10">
                    <img src="/MelisDemoCms/img/erp-home/erp_icon5.png" alt="">
                    <a href="#"><h3 class="h_head">Quick Navigations</h3></a>
                    <p>Bloke fantastic bubble and squeak do one what a plonker nancy boy burke fanny around.</p>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="erp_service_item pl_70">
                    <img src="/MelisDemoCms/img/erp-home/erp_icon6.png" alt="">
                    <a href="#"><h3 class="h_head">Works in Web</h3></a>
                    <p>Bloke fantastic bubble and squeak do one what a plonker nancy boy burke fanny around.</p>
                </div>
            </div>
        </div>
    </div>
</section>