<section class="app_service_area app_service_area_two">
    <div class="container">
        <div class="row app_service_info">
            <div class="col-lg-4 col-sm-6">
                <div class="app_service_item">
                    <i class="ti-settings app_icon one"></i>
                    <h5 class="f_p f_size_18 f_600 t_color3 mt_40 mb-30">Premium plugins</h5>
                    <p class="f_400 f_size_15 mb-30">Oxford jolly good cras bugger down the pub blow off well arse tinkety tonk old fruit William bite your arm off haggle, old it's all gone to pot daft no biggie bog.!</p>
                    <a href="#" class="learn_btn_two c_violet">Learn More <i class="ti-arrow-right"></i></a>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="app_service_item">
                    <i class="ti-heart-broken app_icon two"></i>
                    <h5 class="f_p f_size_18 f_600 t_color3 mt_40 mb-30">Unique elements</h5>
                    <p class="f_400 f_size_15 mb-30">Oxford jolly good cras bugger down the pub blow off well arse tinkety tonk old fruit William bite your arm off haggle, old it's all gone to pot daft no biggie bog.!</p>
                    <a href="#" class="learn_btn_two c_violet">Learn More <i class="ti-arrow-right"></i></a>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="app_service_item">
                    <i class="ti-target app_icon three"></i>
                    <h5 class="f_p f_size_18 f_600 t_color3 mt_40 mb-30">Live page builder</h5>
                    <p class="f_400 f_size_15 mb-30">Oxford jolly good cras bugger down the pub blow off well arse tinkety tonk old fruit William bite your arm off haggle, old it's all gone to pot daft no biggie bog.!</p>
                    <a href="#" class="learn_btn_two c_violet">Learn More <i class="ti-arrow-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>