<section class="blog_area sec_pad cus_ptB_Bl">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="blog_single mb_50">
                    <div class="blog_content cus_p">
                        <blockquote class="blockquote mb_40">
                            <h6 class="mb-0 f_size_18 l_height30 f_p f_400">Elizabeth ummm I'm telling bodge spend a penny say wellies say James Bond, bubble and squeak a such a fibber you mug quaint cack what.!</h6>
                        </blockquote>
                        <p class="f_400 mb-30">Bloke cracking goal the full monty get stuffed mate posh wellies fantastic knackered tickety-boo Harry porkies, mush excuse my French bender down the pub Oxford bum bag gutted mate car boot pukka loo it's your round, cor blimey guvnor is on your bike mate cup of char some dodgy chav blag happy days nancy boy hotpot.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>