<section class="erp_action_area">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4">
                <img src="/MelisDemoCms/img/erp-home/action_img.png" alt="">
            </div>
            <div class="col-lg-9 col-md-8">
                <div class="erp_content">
                    <h2>Trusted by <strong>10,030+ Businesses</strong> over 160 Countries and 24+ Languages</h2>
                </div>
            </div>
        </div>
    </div>
</section>