<section class="sass_partner_logo_area sec_pad">
    <div class="container">
        <div class="sec_title text-center wow fadeInUp" data-wow-delay="0.3s" style="visibility: visible; animation-delay: 0.3s; animation-name: fadeInUp;">
            <h2 class="f_p f_size_30 l_height50 f_600 t_color">We Offer Around 100 Applications</h2>
            <p class="f_400 f_size_16">Well at public school cheeky bugger grub burke codswallop smashing only a quid<br> pardon you lavatory chip shop, geeza loo horse play.</p>
        </div>
        <div class="partner_logo_area_four">
            <div class="row partner_info">
                <div class="logo_item">
                    <a href="#"><img src="/MelisDemoCms/img/home3/logo_01.png" alt=""></a>
                </div>
                <div class="logo_item">
                    <a href="#"><img src="/MelisDemoCms/img/home3/logo_02.png" alt=""></a>
                </div>
                <div class="logo_item">
                    <a href="#"><img src="/MelisDemoCms/img/home3/logo_03.png" alt=""></a>
                </div>
                <div class="logo_item">
                    <a href="#"><img src="/MelisDemoCms/img/home3/logo_04.png" alt=""></a>
                </div>
                <div class="logo_item">
                    <a href="#"><img src="/MelisDemoCms/img/home3/logo_05.png" alt=""></a>
                </div>
                <div class="logo_item">
                    <a href="#"><img src="/MelisDemoCms/img/home3/logo_03.png" alt=""></a>
                </div>
                <div class="logo_item">
                    <a href="#"><img src="/MelisDemoCms/img/home3/logo_04.png" alt=""></a>
                </div>
                <div class="logo_item">
                    <a href="#"><img src="/MelisDemoCms/img/home3/logo_05.png" alt=""></a>
                </div>
            </div>
        </div>
    </div>
</section>