<section class="fun_fact_area dk_bg_two Cus_ffa">
    <div class="container">
        <div class="row flex-row-reverse">
            <div class="col-lg-7 col-md-6">
                <div class="fact_author_img text-right">
                    <div class="square_box box_three"></div>
                    <div class="square_box box_four"></div>
                    <img class="wow fadeInUp" data-wow-delay="0.4s" src="/MelisDemoCms/img/home6/trust_img2.png" alt="" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeInUp;">
                </div>
            </div>
            <div class="col-lg-5 col-md-6">
                <div class="fun_fact_content">
                    <h1 class="w_color f_p f_700 mb_20">Trusted</h1>
                    <p class="f_400 d_p_color f_size_15 l_height28 mb_40">Why I say old chap that is spiffing barney, nancy boy bleeder chimney pot Richard cheers the little rotter so I said, easy peasy buggered blower bevvy A bit of how's your father he nicked it arse over tit. </p>
                    <div class="d-flex">
                        <div class="fact_item">
                            <h1 class="w_color"><span>7</span>M+</h1>
                            <p class="mb-0 d_p_color">Users <br>trust our tools</p>
                        </div>
                        <div class="fact_item pl_100">
                            <h1 class="w_color"><span>100</span>K</h1>
                            <p class="mb-0 d_p_color">Join <br>every month</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>