<section class="pricing_area_two sec_pad">
    <div class="container custom_container p0">
        <div class="tab-content price_content price_content_two">
            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                <div class="row">
                    <div class="col-lg-4 col-sm-6">
                        <div class="price_item">
                            <img src="/MelisDemoCms/img/price/one.png" alt="">
                            <h5 class="f_p f_size_20 f_600 t_color2 mt_30">Education</h5>
                            <p>Create your first online course</p>
                            <div class="price f_700 f_size_40 t_color2">$25.00<sub class="f_size_16 f_400">/ mo</sub></div>
                            <ul class="list-unstyled p_list">
                                <li><i class="ti-check"></i>Only 2 Operators</li>
                                <li><i class="ti-check"></i>Abandoned Cart</li>
                                <li><i class="ti-check"></i>Facebook & Instagram Ads</li>
                                <li><i class="ti-close"></i>Order Notifications</li>
                                <li><i class="ti-close"></i>Landing Pages</li>
                            </ul>
                            <a href="#" class="price_btn btn_hover">Start Today</a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <div class="price_item">
                            <div class="tag"><span>Popular</span></div>
                            <img src="/MelisDemoCms/img/price/two.png" alt="">
                            <h5 class="f_p f_size_20 f_600 t_color2 mt_30">Professional</h5>
                            <p>Our most popular plan</p>
                            <div class="price f_700 f_size_40 t_color2">$25.00<sub class="f_size_16 f_400">/ mo</sub></div>
                            <ul class="list-unstyled p_list">
                                <li><i class="ti-check"></i>Only 2 Operators</li>
                                <li><i class="ti-check"></i>Abandoned Cart</li>
                                <li><i class="ti-check"></i>Facebook & Instagram Ads</li>
                                <li><i class="ti-close"></i>Order Notifications</li>
                                <li><i class="ti-close"></i>Landing Pages</li>
                            </ul>
                            <a href="#" class="price_btn btn_hover">Start Today</a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <div class="price_item">
                            <img src="/MelisDemoCms/img/price/three.png" alt="">
                            <h5 class="f_p f_size_20 f_600 t_color2 mt_30">Business</h5>
                            <p>Experience thebest of lorem</p>
                            <div class="price f_700 f_size_40 t_color2">$99.00<sub class="f_size_16 f_400">/ mo</sub></div>
                            <ul class="list-unstyled p_list">
                                <li><i class="ti-check"></i>Only 2 Operators</li>
                                <li><i class="ti-check"></i>Abandoned Cart</li>
                                <li><i class="ti-check"></i>Facebook & Instagram Ads</li>
                                <li><i class="ti-close"></i>Order Notifications</li>
                                <li><i class="ti-close"></i>Landing Pages</li>
                            </ul>
                            <a href="#" class="price_btn btn_hover">Start Today</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                <div class="row">
                    <div class="col-lg-4 col-sm-6">
                        <div class="price_item">
                            <div class="tag"><span>Popular</span></div>
                            <img src="/MelisDemoCms/img/home2/price-3.png" alt="">
                            <h5 class="f_p f_size_20 f_600 t_color2 mt_30">Professional</h5>
                            <p>Create your first online course</p>
                            <div class="price f_700 f_size_40 t_color2">$25.00<sub class="f_size_16 f_400">/ mo</sub></div>
                            <ul class="list-unstyled p_list">
                                <li><i class="ti-check"></i>Only 2 Operators</li>
                                <li><i class="ti-check"></i>Abandoned Cart</li>
                                <li><i class="ti-check"></i>Facebook & Instagram Ads</li>
                                <li><i class="ti-close"></i>Order Notifications</li>
                                <li><i class="ti-close"></i>Landing Pages</li>
                            </ul>
                            <a href="#" class="price_btn btn_hover">Start Today</a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <div class="price_item">
                            <img src="/MelisDemoCms/img/home2/price-2.png" alt="">
                            <h5 class="f_p f_size_20 f_600 t_color2 mt_30">Education</h5>
                            <p>Create your first online course</p>
                            <div class="price f_700 f_size_40 t_color2">$25.00<sub class="f_size_16 f_400">/ mo</sub></div>
                            <ul class="list-unstyled p_list">
                                <li><i class="ti-check"></i>Only 2 Operators</li>
                                <li><i class="ti-check"></i>Abandoned Cart</li>
                                <li><i class="ti-check"></i>Facebook & Instagram Ads</li>
                                <li><i class="ti-close"></i>Order Notifications</li>
                                <li><i class="ti-close"></i>Landing Pages</li>
                            </ul>
                            <a href="#" class="price_btn btn_hover">Start Today</a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <div class="price_item">
                            <img src="/MelisDemoCms/img/home2/price-1.png" alt="">
                            <h5 class="f_p f_size_20 f_600 t_color2 mt_30">Business</h5>
                            <p>Create your first online course</p>
                            <div class="price f_700 f_size_40 t_color2">$25.00<sub class="f_size_16 f_400">/ mo</sub></div>
                            <ul class="list-unstyled p_list">
                                <li><i class="ti-check"></i>Only 2 Operators</li>
                                <li><i class="ti-check"></i>Abandoned Cart</li>
                                <li><i class="ti-check"></i>Facebook & Instagram Ads</li>
                                <li><i class="ti-close"></i>Order Notifications</li>
                                <li><i class="ti-close"></i>Landing Pages</li>
                            </ul>
                            <a href="#" class="price_btn btn_hover">Start Today</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>