<blockquote class="media blockquote_three">
    <img src="/MelisDemoCms/img/qoute.png" alt="">
    <div class="media-body">
        The HTML<code class="highlighter-rouge">&lt;blockquote&gt;</code> Element (or HTML Block Quotation Element) indicates that the enclosed text is an extended quotation. Usually, this is rendered visually by indentation (see Notes for how to change it). A URL for the source of the quotation may be given using the <code class="highlighter-rouge">&lt;cite&gt;</code> attribute, while a text representation of the source can be given using the element.
    </div>
</blockquote>