<section class="breadcrumb_area" style="z-index: unset !important; background-image: linear-gradient(180deg, #0c4de0 0%, #87acff 100%);">
    <div class="container">
        <div class="breadcrumb_content text-center">
            <h1 class="f_p f_700 f_size_50 w_color l_height50 mb_20">Accessible, Convenient & Manageable</h1>
            <p class="f_400 w_color f_size_16 l_height26">The full monty burke posh excuse my French Richard cheeky bobby spiffing crikey<br> Why gormless, pear shaped.!</p>
        </div>
    </div>
</section>