<section class="erp_banner_area_two">
    <ul class="list-unstyled cloud_animation">
        <li><img src="/MelisDemoCms/img/erp-home/cloud_01.png" alt=""></li>
        <li><img src="/MelisDemoCms/img/erp-home/cloud_02.png" alt=""></li>
        <li><img src="/MelisDemoCms/img/erp-home/cloud_03.png" alt=""></li>
        <li><img src="/MelisDemoCms/img/erp-home/cloud_04.png" alt=""></li>
        <li><img src="/MelisDemoCms/img/erp-home/cloud_05.png" alt=""></li>
        <li><img src="/MelisDemoCms/img/erp-home/cloud_06.png" alt=""></li>
    </ul>
    <div class="erp_shap"></div>
    <div class="erp_shap_two" style="background: url(/MelisDemoCms/img/erp-home/banner_shap.png) no-repeat scroll top left;"></div>
    <div class="section_intro">
        <div class="section_container">
            <div class="intro">
                <div class=" intro_content">
                    <h1>Cloud ERP Software for Small and medium business</h1>
                    <p>A simple and powerful erp software for Manufacturing, Distribution and Services.</p>
                    <a href="#" class="er_btn er_btn_two">Try to Free</a>
                </div>
            </div>
        </div>
    </div>
</section>