<?= $this->MelisDragDropZone($this->idPage, "testimonial_html_1") ?>
<div class="erp_testimonial_item">
    <div class="content">
        <p>
            <?=
                $this->MelisTag(
                    $this->idPage,
                    'testi-html-1',
                    'html',
                    'Loo car boot bodge smashing I up the duff horse play give us a bell, William bugger all mate happy days mush at public school tosser victoria sponge, say lurgy hunky-dory twit hotpot gutted mate.'
                )
            ?>
        </p>
    </div>
    <div class="media">
        <?=
            $this->MelisTag(
                $this->idPage,
                'testi-img-1',
                'html',
                '<img src="/MelisDemoCms/img/erp-home/testimonial_img.jpg" alt="">'
            )
        ?>
        <div class="media-body">
            <h5>
                <?=
                    $this->MelisTag(
                        $this->idPage,
                        'testi-textarea-1',
                        'html',
                        'Lance Bogrol'
                    )
                ?>
            </h5>
            <p>
                <?=
                    $this->MelisTag(
                        $this->idPage,
                        'testi-textarea-2',
                        'html',
                        'Officer at Samumed'
                    )
                ?>
            </p>
        </div>
    </div>
</div>