<section class="error_two_area">
    <div class="container">
        <div class="error_content_two text-center">
            <img src="<?= $this->basePath('MelisDemoCms/img/new/error.png') ?>" alt="">
            <?=
                $this->MelisTag(
                    $this->idPage,
                    '404-html-1',
                    'html',
                    '<h2>Error. We can’t find the page you’re looking for.</h2>
                    <p>Sorry for the inconvenience. Go to our homepage or check out our latest collections for Fashion, Chair, Decoration... </p>
                    <a href="/" class="about_btn btn_hover">Back to Home Page <i class="arrow_right"></i></a>'
                )
            ?>
        </div>
    </div>
</section>
