<section class="breadcrumb_area" style="z-index: unset !important;">
    <div class="container">
        <?=
            $this->MelisTag(
                $this->idPage,
                'team-html-1',
                'html',
                '<div class="hosting_title erp_title text-center">
                    <h1 class="f_p f_700 f_size_50 w_color l_height50 mb_20">Meet The Team</h1>
                    <p class="f_400 w_color f_size_16 l_height26">Why I say old chap that is spiffing off his nut arse pear shaped plastered<br> Jeffrey bodge barney some dodgy.!!</p>
                </div>'
            )
        ?>
    </div>
</section>

<section class="experts_team_area sec_pad">
    <div class="container">
        <!-- Title Subtitle Centered Mini Template -->
        <?=
            $this->MelisTag(
                $this->idPage,
                'team-html-2',
                'html',
                '<div class="hosting_title erp_title text-center">
                    <h2>The Experts Team</h2>
                    <p>Why I say old chap that is spiffing barney, nancy boy bleeder chimney<br> pot richard cheers the little rotter.!</p>
                </div>'
            )
        ?>
        <div class="col-lg-12">
            <!-- Team Slider Plugin -->
            <?= $this->teamSlider ?>
        </div>
    </div>
</section>