<?= $this->MelisDragDropZone($this->idPage, "dragdropzone_team_1") ?>
<div class="clear"></div>
<section class="experts_team_area sec_pad">
    <div class="container">
        <!-- Title Subtitle Centered Mini Template -->
        <?=
            $this->MelisTag(
                $this->idPage,
                'team-html-2',
                'html',
                '<div class="hosting_title erp_title text-center">
                    <h2>The Experts Team</h2>
                    <p>Why I say old chap that is spiffing barney, nancy boy bleeder chimney<br> pot richard cheers the little rotter.!</p>
                </div>'
            )
        ?>
        <div class="col-lg-12">
            <!-- Team Slider Plugin -->
            <?= $this->teamSlider ?>
        </div>
    </div>
</section>
<?= $this->MelisDragDropZone($this->idPage, "dragdropzone_team_2") ?>
<div class="clear"></div>
