<?= $this->MelisDragDropZone($this->idPage, "dragdropzone_news_details_1") ?>
<section class="blog_area sec_pad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 blog_sidebar_left">
                <!-- News details plugin -->
                <?= $this->newsDetails ?>
            </div>
            <div class="col-lg-4">
                <!-- Latest news plugin -->
                <?= $this->latestNews ?>
            </div>
        </div>
    </div>
</section>
<?= $this->MelisDragDropZone($this->idPage, "dragdropzone_news_details_2") ?>
