<section class="breadcrumb_area" style="z-index: unset !important;">
    <div class="container">
        <?=
            $this->MelisTag(
                $this->idPage,
                'newsd-html-1',
                'html',
                '<div class="breadcrumb_content text-center">
                    <h1 class="f_p f_700 f_size_50 w_color l_height50 mb_20">News Details</h1>
                    <p class="f_400 w_color f_size_16 l_height26">Why I say old chap that is spiffing off his nut arse pear shaped plastered<br> Jeffrey bodge barney some dodgy.!!</p>
                </div>'
            )
        ?>
    </div>
</section>

<section class="blog_area sec_pad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 blog_sidebar_left">
                <!-- News details plugin -->
                <?= $this->newsDetails ?>
            </div>
            <div class="col-lg-4">
                <!-- Latest news plugin -->
                <?= $this->latestNews ?>
            </div>
        </div>
    </div>
</section>
