<div style="height: 100px;"></div>
<!-- Title subtitle centered mini template  -->
<section class="erp_service_area sec_pad">
    <div class="container">
        <?=
            $this->MelisTag(
                $this->idPage,
                'srv-html-1',
                'html',
                '<div class="hosting_title erp_title text-center">
                <h2>How We Work</h2>
                <p>The full monty burke posh excuse my French Richard cheeky bobby spiffing crikey<br> Why gormless, pear shaped.!</p>
            </div>'
            )
        ?>
    </div>
</section>
<!-- 3 cols in blocks mini template  -->
<?=
    $this->MelisTag(
        $this->idPage,
        '3-cols-in-blocks',
        'html',
        '<section class="app_service_area app_service_area_two">
            <div class="container">
                <div class="row app_service_info">
                    <div class="col-lg-4 col-sm-6">
                        <div class="app_service_item">
                            <i class="ti-settings app_icon one"></i>
                            <h5 class="f_p f_size_18 f_600 t_color3 mt_40 mb-30">Premium plugins</h5>
                            <p class="f_400 f_size_15 mb-30">Oxford jolly good cras bugger down the pub blow off well arse tinkety tonk old fruit William bite your arm off haggle, old it\'s all gone to pot daft no biggie bog.!</p>
                            <a href="#" class="learn_btn_two c_violet">Learn More <i class="ti-arrow-right"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <div class="app_service_item">
                            <i class="ti-heart-broken app_icon two"></i>
                            <h5 class="f_p f_size_18 f_600 t_color3 mt_40 mb-30">Unique elements</h5>
                            <p class="f_400 f_size_15 mb-30">Oxford jolly good cras bugger down the pub blow off well arse tinkety tonk old fruit William bite your arm off haggle, old it\'s all gone to pot daft no biggie bog.!</p>
                            <a href="#" class="learn_btn_two c_violet">Learn More <i class="ti-arrow-right"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <div class="app_service_item">
                            <i class="ti-target app_icon three"></i>
                            <h5 class="f_p f_size_18 f_600 t_color3 mt_40 mb-30">Live page builder</h5>
                            <p class="f_400 f_size_15 mb-30">Oxford jolly good cras bugger down the pub blow off well arse tinkety tonk old fruit William bite your arm off haggle, old it\'s all gone to pot daft no biggie bog.!</p>
                            <a href="#" class="learn_btn_two c_violet">Learn More <i class="ti-arrow-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>'
    )
?>
<!-- 3 cols left text right image mini template -->
<?=
    $this->MelisTag(
        $this->idPage,
        '2-cols-left-text-right-image',
        'html',
        '<section class="erp_features_area_two sec_pad">
            <div class="container">
                <div class="row erp_item_features align-items-center flex-row-reverse">
                    <div class="col-lg-6">
                        <div class="erp_features_img_two">
                            <div class="img_icon"><span class="pluse_1"></span><span class="pluse_2"></span><i class="icon_lightbulb_alt"></i></div>
                            <img src="' . $this->basePath('/MelisDemoCms/img/erp-home/crm_img1.jpg') . '" alt="">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="erp_content_two">
                            <div class="hosting_title erp_title">
                                <h2 class="f_p f_600 f_size_30 t_color3 l_height40 mb-30">Predictive and imperative approach towards software.</h2>
                                <p class="f_400 mb_50">Why I say old chap that is spiffing pukka, bamboozled wind up bugger buggered zonked hanky panky a blinding shot the little rotter, bubble and squeak vagabond cheeky.!</p>
                                <br>
                                <ul class="list-unstyled mb-30 pl-0 pr_20">
                                    <li><i class="ti-check"></i>&nbsp;Only a quid I dropped a clanger matie boy excuse my French hanky.</li>
                                    <li><i class="ti-check"></i>&nbsp;Panky pardon you me old mucker bum bag, bevvy bloke it\'s all gone to pot.</li>
                                    <li><i class="ti-check"></i>&nbsp;Ummm I\'m telling bits and bobs mush baking cakes car boot.</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>'
    )
?>
<!-- 3 cols right text left image mini template  -->
<?=
    $this->MelisTag(
        $this->idPage,
        '2-cols-right-text-left-image',
        'html',
        '<section class="erp_features_area_two sec_pad">
            <div class="container">
                <div class="row erp_item_features align-items-center">
                    <div class="col-lg-6">
                        <div class="erp_features_img_two">
                            <div class="img_icon red"><span class="pluse_1"></span><span class="pluse_2"></span><i class="icon_lightbulb_alt"></i></div>
                            <img src="'. $this->basePath('/MelisDemoCms/img/erp-home/crm_img2.jpg') . '" alt="">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="erp_content_two">
                            <div class="hosting_title erp_title">
                                <h2 class="f_p f_600 f_size_30 t_color3 l_height40 mb-30">Social intranet software that<br> drives employee engagement and productivity.</h2>
                                <p class="f_400 mb_40">Why I say old chap that is spiffing pukka, bamboozled wind up bugger buggered zonked hanky panky a blinding shot the little rotter, bubble and squeak vagabond cheeky.!</p>
                            </div>
                            <a href="#" class="erp_btn_learn">View More About<i class="arrow_right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>'
    )
?>