<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <?php $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->basePath('/MelisDemoCms/img/melis-favicon.ico'), 'PREPEND')); ?>

    <!-- Append css files from controller -->
    <?php if (! empty($this->pageCss)) : ?>
        <?php foreach ($this->pageCss as $key => $css) : ?>
            <?php $this->headLink()->appendStylesheet($css) ?>
        <?php endforeach; ?>
    <?php endif; ?>

    <!-- List CSS files. Located at /config/assets.config.php -->
    <?= $this->headLink() ?>
</head>
<body style="<?= ($this->renderMode == 'melis' ? 'padding-top: 50px;' : '') ?>">
<div class="body_wrapper">
    <header class="header_area">
        <nav class="navbar navbar-expand-lg menu_one menu_four" style="<?= ($this->renderMode == 'melis' ? 'padding-top: 50px;' : '') ?>">
            <div class="container">
                <a class="navbar-brand" href="/" style="padding-right: 40px;padding-left: 8px; margin-top: 7px;"><img src="<?= $this->basePath('/MelisDemoCms/img/melis-logo.svg') ?>" style="width: 30px; float: left;"><h4 style="letter-spacing: -2px;font-weight: 600;color: #e61c23;">&nbsp Melis Demo Cms</h4></a>
                <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="menu_toggle">
                        <span class="hamburger">
                            <span class="<?= ($this->menuFlag == 'black') ? 'custom-hamburger-color' : '' ?>"></span>
                            <span class="<?= ($this->menuFlag == 'black') ? 'custom-hamburger-color' : '' ?>"></span>
                            <span class="<?= ($this->menuFlag == 'black') ? 'custom-hamburger-color' : '' ?>"></span>
                        </span>
                        <span class="hamburger-cross">
                            <span class="<?= ($this->menuFlag == 'black') ? 'custom-hamburger-color' : '' ?>"></span>
                            <span class="<?= ($this->menuFlag == 'black') ? 'custom-hamburger-color' : '' ?>"></span>
                        </span>
                    </span>
                </button>

                <!-- Add menu -->
                <?= $this->layout()->menu ?>
            </div>
        </nav>
    </header>
    <div style="height: 93px;"></div>
    <?= $this->content; ?>
    <footer class="footer_area h_footer_dark h_footer_dark_two">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="f_widget dark_widget company_widget">
                        <a href="/" class="f-logo">
                            <img src="<?= $this->basePath('/MelisDemoCms/img/melis-logo.svg') ?>" alt="" style="width: 70px; float: left;margin-top: -5px;">
                            <h4 style="letter-spacing: -2px;font-weight: 600;color: #e61c23;">&nbsp Melis &nbsp Demo &nbsp Cms <br> &nbsp for &nbsp MELISPLATFORM</h4>
                        </a>
                        <p>© <?= date('Y') ?> Melis Technology <br> All rights reserved</p>
                        <div class="f_social_icon">
                            <a href="https://www.facebook.com/melistechnology" class="ti-facebook"></a>
                            <a href="https://twitter.com/meliscms" class="ti-twitter-alt"></a>
                            <a href="https://www.linkedin.com/company/melis-technology" class="ti-linkedin"></a>
                            <a href="#" class="ti-youtube"></a>
                        </div>
                    </div>
                </div>

                <!-- Add footer menu -->
                <div class="col-lg-8">
                    <?= $this->footerMenu ?>
                </div>
            </div>
        </div>
    </footer>
</div>

<!-- Optional JavaScript -->

<!-- Append js files added from controller -->
<?php if (! empty($this->pageJs)) : ?>
    <?php foreach ($this->pageJs as $key => $js) : ?>
        <?php $this->inlineScript()->appendFile($js) ?>
    <?php endforeach; ?>
<?php endif; ?>

<!-- List all js files. Located at /config/assets.config.php -->
<?= $this->inlineScript(); ?>
<!-- No conflict fix with page edition | tiny mce  -->
<script type="text/javascript">
    <?php if ($this->renderMode == 'melis') : ?>
        var jQuery_3_2_1 = $.noConflict(true);
    <?php endif; ?>
</script>
</body>
</html>